# Generated by Django 4.1.3 on 2022-11-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_post_deatail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deatail',
            new_name='detail',
        ),
    ]
