# Generated by Django 4.1.3 on 2022-11-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_post_image_alter_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
